import Image from "next/image";
import Button from "@mui/material/Button";

const pools = [
  {
    name: "1",
    description: "some details",
    href: "https://swap.dodoex.io/StarSeeds_Exchange",
    poolpercentage: "For Protocols",
    pooldescription:
      "StarSeeds Protocol provides DEXs, Automated Liquidity Management, Lending, Synthetics & Bridging Protocols with long-term, recurring & compounding trade volume, liquidity, and staked holdings. ",
  },
  {
    name: "2",
    description: "some details",
    href: "#",
    poolpercentage: "For Traders",
    pooldescription:
      "Benefit from StarSeeds Protocol’s adaptive portfolio of DEX trading options and vetted trading signals and private market data. ",
  },
  {
    name: "3",
    description: "some details",
    href: "#staking",
    poolpercentage: "For Liquidity Providers",
    pooldescription:
      "Obtain better returns while holding the same tokens in StarSeeds Protocol’s Arbitrage Liquidity Pool Routers (Built on Balancer’s Weighted Pool and Arbitrage systems) that benefit from greatly increased trading volume generated by arbitrage trading bot networks.",
  },
];

export default function StarseedsDao() {
  return (
    <section className="lg:w-full w-[90%] flex justify-center mx-auto items-center py-8">
      <div className="flex flex-col-reverse items-center justify-center gap-8">
        <div>
          <div className="my-8">
            <div className=" text-lg lg:text-4xl font-semibold text-[#d4d4d4] mb-6 text-left">
              StarSeeds Protocol Dao
            </div>
            <div className="text-left text-lg lg:text-xl font-medium mx-auto text-[#d4d4d4]">
              StarSeeds Protocol connects users with Automated Liquidity
              Management, Lending, Synthetics & Bridging Protocols with
              long-term, recurring & compounding trade volume, liquidity, and
              staked holdings.
            </div>
          </div>
          <div className="flex flex-wrap my-4 gap-8 mx-auto">
            {pools.map((item) => (
              <div
                key={item.name}
                className="w-full min-h-[7.5rem] p-4 pl-0 pt-0 mx-auto"
              >
                <div className="w-full">
                  <div className="text-xl font-medium text-gray-300 text-left normal-case mt-4 mb-2">
                    {item.poolpercentage}
                  </div>
                  <div className="text-base text-gray-400 font-extralight text-left normal-case min-h-12">
                    {item.pooldescription}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
